### PR TITLE
update with 2018.3 version

### PR DESCRIPTION
**Pull request by Jimexist**

### CODE REVIEW

**Comment by eroispaziali** [comment]
@mplushnikov it would be awesome if you could please take a look and push a new release out if this is okay! Thanks!

**Comment by zgranik** [comment]
@mplushnikov are you alive :) ?

**Comment by mplushnikov** [comment]
@zgranik , Yes, I'm alive, but currently moving to another apartment and don't have time to do something:(

**Comment by mplushnikov** [comment]
Thnak you for your work @Jimexist !

**Comment by zgranik** [comment]
Thank god, I hope the update will work :)

**Comment by fungbo** [comment]
Waiting for the release contains the change

**Comment by eroispaziali** [comment]
Hi @mplushnikov thanks for merging this in. I think a number of people like me are holding off their IntelliJ upgrade to the latest 2018.3.X and are waiting for this to become officially available [here](https://plugins.jetbrains.com/plugin/6317-lombok-plugin). 

I am not familiar with the process, but I assume is automated and perhaps tagging a new release is just what we need for this to happen? Could please you do it when you get a chance, it would be massively appreciated! Thanks and good look with moving to your new flat!

**Comment by mplushnikov** [comment]
Hi @eroispaziali,
I'm ashamed to admit it, but it's a very time-consuming and manual process right now. :-( I'm wondering how to automate it with Travis. Maybe I'll be on it this weekend...

**Pull request merged**
