### PR TITLE
Add Builder setterPrefix #719

### LINKED ISSUE #719: Support new setterPrefix for Builder
See https://github.com/rzwitserloot/lombok/pull/2174

Syntax:
```
@Builder(setterPrefix = "with")
class ...

builder.withOne(one)
       .withTwo(two)
       .build();
```

@mplushnikov how many hours would you bet on this one?

### PR DESCRIPTION
**Pull request by ocadaruma**
This PR fixes #719

Hi, thank you for useful plugin.
I added a support for `@Builder(setterPrefix)`. Could you take a look ?

image

### CODE REVIEW

**Comment by Dikshit-Ram** [comment]
@ocadaruma The build failed. Would you mind looking into it, please?

**Comment by ocadaruma** [comment]
Hm, right...
Let me check

**Comment by ocadaruma** [comment]
@mplushnikov Hi, I found that the CI failure of this PR is solved by disabling cache.
- failed: https://travis-ci.org/mplushnikov/lombok-intellij-plugin/builds/653689836
- succeeded: https://travis-ci.org/mplushnikov/lombok-intellij-plugin/builds/653687316

The only difference is https://github.com/mplushnikov/lombok-intellij-plugin/commit/6c30039c1eb232887cae968a369dd9884c113cf2

Could you clear travis build cache once ?

**Comment by mplushnikov** [comment]
Hello @ocadaruma 

thank you very much for your contribution. I'll look on your PR next days!
Can you please add yourself to contributors list from readme.md file?

**Comment by Dikshit-Ram** [comment]
@mplushnikov Can you please provide me with a date this feature will be released? Our team is heavily dependent on this and we have been forced to use other IDEs in meanwhile.

**Comment by ocadaruma** [comment]
Thank you for your quick review !
I added myself to contributors list.

**Pull request merged**
