### PR TITLE
Remove discouraged usages of Constructor Injection

### PR DESCRIPTION
**Pull request by GingerGeek**
Usage of Project#getService requires IDEA version 193.5233.102 so the minimum version is set to 201.00

### CODE REVIEW

**Comment by DaMatrix** [comment]
Not sure what the status on this PR is, but there are still a lot of exceptions when trying to use this with 2020.2.

[stacktrace.txt](https://pastebin.com/JdwL9MV1)
[induced.txt](https://pastebin.com/khsWhNQT)

**Comment by GingerGeek** [comment]
Yeah, I tried to figure out how to fix the psi issues but got nowhere - I did some debug where I forced lombok psi to always be valid but this then caused the index to desync which sounds dangerous!

These changes are just some maintenance tasks I did to get familiar with the code base - functionally the do nothing except remove some platform warnings.

**Comment by mplushnikov** [comment]
Thank you for your improvement, I'm in vacation and will look on it as soon as I'l be back.

**Comment by mplushnikov** [comment]
Thank you @GingerGeek , just merged this pr.

**Pull request merged**
