### PR TITLE
#645. Potential fix of find usages for builder's pseudo-fields

### PR DESCRIPTION
**Pull request by Lekanich**
- add as source real navigated field for pseudo-builder field
 - should fix issue #645

### CODE REVIEW

**Comment by mplushnikov** [comment]
Thank you again @Lekanich ! Will review it the next days...

**Comment by mplushnikov** [comment]
Can you better explain me your understanding of #645? I'm not really sure to properly understand, what  Artemiy is expected...

**Comment by Lekanich** [comment]
> Can you better explain me your understanding of #645? I'm not really sure to properly understand, what Artemiy is expected...
I guess he expected something like that (as on the picture). But we should try to ask him. And to do this we need Psi tree inside builder methods but it's redundant information for all other parts, IMHO.
image

I thought that we can add an explicit connection between the light builder field and his original field.
But after re-reading in the tenth time his issue I guess it doesn't help him. I start to wavering.

**Comment by Lekanich** [comment]
Okay, it's almost a year since no feedback from the reporter. I gonna close that PR because I'm not sure that those changes are a good idea.

**Pull request closed without merging**
