### PR TITLE
#547 Implement FieldNameConstants for lombok 1.18.4

### PR DESCRIPTION
**Pull request by alanachtenberg**
So this was my first time trying to work with the intellij sdk at this level. Creating a light enum and enum constants properly was most difficult. I started with trying to extend the class builder and field builder but ran into so many issues either in the tests or in the IDE. I ended up taking the delegate approach and think i got all the issues ironed out. 

One thing that is obviously missing is backwards compatibility for 1.18.2 and older.
I didn't want to waste time with it if its not needed.
How do you normally manage version specific changes/backwards compatability? 
Would you register a different processor depending on (detected?? configured?) lombok version?

Please let me know if you have any feedback.
Thanks,

Alan

### CODE REVIEW

**Comment by alanachtenberg** [comment]
I see a unit test i added failed. Pretty sure i tested it locally but i will retest it this evening.

**Comment by alanachtenberg** [comment]
Hi @mplushnikov. Have you had a chance to take a look yet? Sorry to bother you as I know we get busy, but I am eager to see this feature working :).

**Comment by mplushnikov** [comment]
Hello @alanachtenberg,
I started just today to look on your PR. I already wanted to do it last weekend, but was unfortunately ill :-(
It look very good so far i saw already. I'll just test/verify your enum implementation and try to figure out, why existing LombokLightClassBuilder couldn't be used for it.
I will continue tomorow! Thank you for your work!

**Comment by mplushnikov** [comment]
Because of missing backwards compatibility, I think it should be ok here. 
@FieldNameConstants is marked as "experimental" by lombok, so any changes should be already accepted. 
Supporting both version would be possible, but need some kind of configuration, like selection of current version in plugin-settings.

**Comment by mplushnikov** [comment]
@alanachtenberg 
I just finished looking on your PR:-) 
I created new branch (https://github.com/mplushnikov/lombok-intellij-plugin/tree/rework_enum_support) with some changes. Can you please verify it in your environment? I think you have more code using FieldNameConstants as I have. 
I replaced your new LightEnum classes by extensions of existing class and field builder. It seems to work, but maybe you can double check it, because you wrote you have had some issues with it... 

Please also add yourself to the list of contributors in README.md! 

If everithing will be fine, I would merge it and you can start thinking about implementation of "FEATURE: The @FieldNameConstants feature now allows you to write the inner type by hand and add whatever you like to it; lombok will add the constants to this class. See the updated FieldNameConstants feature page." from https://projectlombok.org/download-edge 🥇

**Comment by alanachtenberg** [comment]
@mplushnikov Thanks for investing time on this. I see you did a few things differently in the class builder that i missed in my first attempt among some other things. The experience shows thank you! I did run into one problem however, the enum `values` and `valueOf` method fails to resolve in IDE. To fix I modified the builder to implement `PsiExtensibleClass` 

with
```
 private ClassInnerStuffCache myInnerCache = new ClassInnerStuffCache(this);

  @NotNull
  @Override
  public List<PsiField> getOwnFields() {
    return Arrays.asList(getFields());
  }

  @NotNull
  @Override
  public List<PsiMethod> getOwnMethods() {
    return Arrays.asList(getMethods());
  }

  @NotNull
  @Override
  public List<PsiClass> getOwnInnerClasses() {
    return Arrays.asList(getInnerClasses());
  }
```

and override the following.

```
  @Override
  public boolean processDeclarations(@NotNull PsiScopeProcessor processor, @NotNull ResolveState state, PsiElement lastParent, @NotNull PsiElement place) {
    if (isEnum()) {
      if (!PsiClassImplUtil.processDeclarationsInEnum(processor, state, myInnerCache)){
        return false;
      }
    }
    return super.processDeclarations(processor, state, lastParent, place);
  }
```
This seems to do the trick. I realized in my original attempt i also missed that the enum needed to call both methods to resolve everything properly. The things you see the second time around :). I will add those enum methods to the manual test and the fix with everything tomorrow if that's okay?

**Comment by mplushnikov** [comment]
@alanachtenberg Great, thank you!

**Comment by alanachtenberg** [comment]
@mplushnikov I opened a new PR with all the changes https://github.com/mplushnikov/lombok-intellij-plugin/pull/587.

Yes that should be fun. I'm interested to see how lombok manages merging the enum.

**Comment by mplushnikov** [comment]
@alanachtenberg Just merged your new PR. Will close this old one!
Thank you for your work!
P.S. Lombok 1.18.6 released today already:)

**Pull request closed without merging**
