### PR TITLE
Fix issue #775 compatibility with IDEA 2020.1

### PR DESCRIPTION
**Pull request by burka**
For comapatibility with IDEA 2020.1 I upgraded the intellij dependency. It works for me :-).

### CODE REVIEW

**Comment by donbeave** [comment]
IDEA 2020.1 is released: https://confluence.jetbrains.com/display/IDEADEV/IntelliJ%2BIDEA%2B2020.1%2B%28201.6668.121%2Bbuild%29%2BRelease%2BNotes?utm_source=product&utm_medium=link&utm_campaign=TBA

When you plan to merge this fix?

**Comment by slturo** [comment]
Please release if possible.

**Comment by x9nico** [comment]
Should be good.

**Comment by SV27** [comment]
will it be released today ? I just upgraded my intellij and almost my entire workspace is blinking in RED.

**Comment by jasonjoneski** [comment]
> will it be released today ? I just upgraded my intellij and almost my entire workspace is blinking in RED.

@mplushnikov  👍

**Comment by mplushnikov** [comment]
you don't need this for 2020.1, but i can merge it anyway...

**Comment by SV27** [comment]
@burka  - Thanks for the fix. Today i updated the plugin and it works.
@mplushnikov  - Thanks for merging and release it.

**Comment by donbeave** [comment]
Is it released? Looks like here the version didn't update yet: https://plugins.jetbrains.com/plugin/6317-lombok

**Comment by bandrefilipe** [comment]
> Is it released? Looks like here the version didn't update yet: https://plugins.jetbrains.com/plugin/6317-lombok

Same here. Update isn't available yet.

**Pull request merged**
