### PR TITLE
Readme: clean up and update

### PR DESCRIPTION
**Pull request by Abrasha**
- Fix Intellij link
- Fix author link to github
- Add _kbd_ tags
- Update dependency examples to latest stable version (1.16.14)

Also, there are two more questions:

- Should we update copyright to 2017?
- Was this invalid URL parameter `?pr=idea plugin` necessarry?

### CODE REVIEW

**Comment by Abrasha** [comment]
Because no sources were changed, build is broken due to different issues.
Build fails only with EAP IDEA.

**Comment by AlexejK** [comment]
The link changed on Jetbrains side most likely. Both actually work fine but good to have version updates

**Comment by KroArtem** [comment]
Lombok version is 1.16.16, to be precise.

**Comment by Abrasha** [comment]
@KroArtem should we update ReadMe to 1.16.16?

**Comment by KroArtem** [comment]
@Abrasha, I don't know. I saw 1.16.16 was released several days ago and it works ok in IDEA.

**Comment by Abrasha** [comment]
@mplushnikov, what do you think about including 1.16.16 to master Readme.md?

**Comment by AlexejK** [comment]
no new features are added but we can always add 1.16.16. should not REALLY matter as we don't rely on anything new in it

**Pull request merged**
