### PR TITLE
Updated gradle.properties to support 2018.2 IntelliJ

### PR DESCRIPTION
**Pull request by 1337c0der**
I don't know if it's gonna work with the IntelliJ version but 
just opening the PR up so that maintainers can look at it and 
decide to merge it if this is the only change needed.

### CODE REVIEW

**Comment by ElzioJunior** [comment]
Thank You!

**Comment by kirillgroshkov** [comment]
It works even without it, as described here: https://github.com/mplushnikov/lombok-intellij-plugin/issues/508

But still it's good to get the warning removed not to confuse users.

**Comment by kirillgroshkov** [comment]
Maybe even put `2018.3` there to be a little bit future proof:)

**Comment by KZeillmann** [comment]
@mplushnikov seems to be missing. Does anyone else have the ability to merge this PR? It's troubling that such a popular and useful plugin wouldn't have any active maintainers to merge PRs.

**Comment by mplushnikov** [comment]
Thank you @1337c0der, I just updated master to new versions

**Pull request closed without merging**
