### PR TITLE
Field defaults support

### LINKED ISSUE #147: @FieldDefaults(makeFinal = true) and bitwise operators produce an error message
This is fine:

```java
class A {
	final short s1 = 2;
	final short s2 = 4;

	void foo() {
		short s3 = s1 ^ s2;
	}
}
```

This compiles and runs but produces an error message when looking into the class:
```java
@FieldDefaults(makeFinal = true)
class A {
	short s1 = 2;
	short s2 = 4;

	void foo() {
		short s3 = s1 ^ s2;
	}
}
```

Same with this:
```java
@FieldDefaults(makeFinal = true)
class A {
	short s1 = 2;
	short s2 = 4;

	void foo() {
		short s3 = 1;
		switch (s3) {
			case s1 | s2:
				break;
		}
	}
}
```

It looks like the compiler does not see that the fields are final when checking bitwise operators.

### PR DESCRIPTION
**Pull request by AlexejK**
Fixes #147 

Supports both `makeFinal` and `level` setting for class fields.
Supports handling of exceptional cases, such as `@NonFinal` and `@PackagePrivate`

### CODE REVIEW

**Comment by AlexejK** [comment]
This should replace #4 for main functionality of `@FieldDefaults`.
I am not sure if we should provide inspections for how "sensible" certain parameters are. If something doesn't make sense - as long as compiler/lombok accepts them, it should be fine for the user to use them.

**Comment by mplushnikov** [comment]
Thank you Alexej! Looks good for me, can you merge conflicts please?

**Comment by AlexejK** [comment]
Ahh you merged the other PR. Yes, will fix that in a second

**Comment by AlexejK** [comment]
should be fixed now. Lets see if Travis still likes it

**Pull request merged**
